.TH voaAreaPlotgui 1 "FEV 2024" Linux "User Manuals"
.SH NAME
voaAreaPlotgui \- Graphical frontend to the voaAreaPlot application
.SH SYNOPSIS
.B voaAreaPlotgui file
.SH DESCRIPTION
.B voaAreaPlotgui
is a graphical user interface to the voaAreaPlot application. It plots the file contents according to the parameters set on the user interface.
.SH AUTHORS
This program was written by James Watson (M0DNS) <jimwatson at mac dot com>.

This manual page was written by David da Silva Polverari <polverari@debian.org>
for the Debian Project (but may be used by others).
