.TH voacapgui 1 "FEV 2024" Linux "User Manuals"
.SH NAME
voacapgui \- An input GUI for voacapl
.SH SYNOPSIS
.B voacapgui
.SH DESCRIPTION
.B voacapgui
is a graphical user interface frontend for \fBvoacapl\fP. It generates voacap input files from user input data and plots the resulting predictions.
.SH AUTHORS
This program was written by James Watson (M0DNS) <jimwatson at mac dot com>.

This manual page was written by David da Silva Polverari <polverari@debian.org>
for the Debian Project (but may be used by others).
