.TH voaP2PPlotgui 1 "FEV 2024" Linux "User Manuals"
.SH NAME
voaP2PPlotgui \- Graphical frontend to the voaP2PPlot application
.SH SYNOPSIS
.B voaP2PPlotgui file
.SH DESCRIPTION
.B voaP2PPlotgui
is a graphical user interface to the voaP2PPlot application. It plots the file contents according to the parameters set on the user interface.
.SH AUTHORS
This program was written by James Watson (M0DNS) <jimwatson at mac dot com>.

This manual page was written by David da Silva Polverari <polverari@debian.org>
for the Debian Project (but may be used by others).
